apiVersion: v1
kind: Service
metadata:
  name: api-external
spec:
  type: NodePort
  ports:
  - name: http
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: api

---

apiVersion: v1
kind: Service
metadata:
  name: ras-external
spec:
  type: NodePort
  ports:
  - name: couchdbport
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    app: ras

---

apiVersion: v1
kind: Service
metadata:
  name: cps-external
spec:
  type: NodePort
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: cps

---

apiVersion: v1
kind: Service
metadata:
  name: metrics-external
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app: metrics

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
spec:
  selector: 
    app: prometheus
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090 

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-external
spec:
  selector: 
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000 
    