apiVersion: v1
kind: Service
metadata:
  name: resource-monitor-external
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  - name: health
    port: 9011
    protocol: TCP
    targetPort: 9011
  selector:
    app: resource-monitor
    
---

apiVersion: v1
kind: Service
metadata:
  name: engine-controller-external
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  - name: health
    port: 9011
    protocol: TCP
    targetPort: 9011
  selector:
    app: engine-controller
    
---

apiVersion: v1
kind: Service
metadata:
  name: metrics-health-external
spec:
  type: NodePort
  ports:
  - name: health
    port: 9011
    protocol: TCP
    targetPort: 9011
  selector:
    app: metrics 