apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-monitor
  labels:
    app: resource-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-monitor
  template:
    metadata:
      name: resource-monitor
      labels:
        app: resource-monitor
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: resource-monitor
        image: docker.galasa.dev/galasa-ibm-boot-embedded-amd64:${dockerVersion}
        imagePullPolicy: Always
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --resourcemanagement
        - --bootstrap
        - $(BOOTSTRAP_URI)
        - --trace
        env:
        - name: BOOTSTRAP_URI
          valueFrom:
            configMapKeyRef:
              name: config
              key: bootstrap
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        livenessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: resource-monitor
  labels:
    app: resource-monitor
spec:
  ports:
  - port: 9010
    name: metrics
    targetPort: 9010
  - port: 9011
    name: health
    targetPort: 9011
  selector:
    app: resource-monitor